title: Jameslb666 的学术主页
description: 记录研究、发布文章、展示项目
url: "https://jameslb666.github.io"
baseurl: ""
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
lang: zh
